name: Go
on: 
   workflow_dispatch:

jobs:
  ci:
    name: "run linting"
    strategy:
      fail-fast: true
      matrix:
        os:  ["ubuntu-latest"]
        go:  ['1.22']
    runs-on: ${{ matrix.os }}
    steps:
    - name: "checkout"
      uses: actions/checkout@v4
    - name: "fetch unshallow"
      run: git fetch --prune --unshallow
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "${{ matrix.go }}"
        cache: false
    - run: go version
